### ISSUE TITLE
Audio plug-ins cannot be enabled

### ISSUE THREAD

**Issue by Techi-Joe** [Sneeds-Feed-and-Seed/sneedacity#57] opened 2021-07-07 01:05 UTC
**Describe the bug**
When using the "Add/Remove plug-ins" option in either the Generate or Effect or Analyze or Tools drop down menu, enabling effects does nothing and re-entering the menu shows them all as disabled again.

**To Reproduce**
1. Go to either Generate or Effect or Analyze or Tools drop down menu
2. Click on "Add/Remove plug-ins"
3. Click select all
4. Click enable
5. Click ok
6. None of the effects are enabled, as you will see if you repeat steps 1-2

**Expected behavior**
plugins enabled in drop-down

**Additional information (please complete the following information):**
 - OS: Manjaro Linux (Plasma) 
 - Version: Sneedacity 3.0.4-alpha-20210706
 
logs:

19:54:41: Sneedacity 3.0.4-alpha-20210706
19:54:41: Warning: Cannot set locale to language "English".
19:54:41: Warning: Critical Nyquist files could not be found. Nyquist effects will not work.
19:54:45: Trying to load FFmpeg libraries...
19:54:45: Trying to load FFmpeg libraries from system paths. File name is 'libavformat.so.58'.
19:54:45: Checking for monolithic avformat from 'libavformat.so.58'.
19:54:45: avformat not monolithic
19:54:45: Loading avutil from '/usr/lib/libavutil.so.56.70.100'.
19:54:45: Loading avcodec from '/usr/lib/libavcodec.so.58.134.100'.
19:54:45: Loading avformat from 'libavformat.so.58'.
19:54:45: Actual avutil path /usr/lib/libavutil.so.56.70.100
19:54:45: Actual avcodec path /usr/lib/libavcodec.so.58.134.100
19:54:45: Actual avformat path /usr/lib/libavformat.so.58.76.100
19:54:45: Importing symbols...
19:54:45: All symbols loaded successfully. Initializing the library.
19:54:45: Retrieving FFmpeg library version numbers:
19:54:45: AVCodec version 0x3a8664 - 58.134.100 (built against 0x3a8664 - 58.134.100)
19:54:45: AVFormat version 0x3a4c64 - 58.76.100 (built against 0x3a4c64 - 58.76.100)
19:54:45: AVUtil version 0x384664 - 56.70.100 (built against 0x384664 - 56.70.100)
19:54:45: FFmpeg libraries loaded successfully.

I had to add a strange tag to makepkg in order for the build to work, here's the command I used in full:
makepkg -csi DOCBOOK_TO_MAN="xmlto man --skip-validation"

**Comment by ishimotoshinobu** [comment] 2021-07-07 01:09
Can you post debug logs?

**Comment by Techi-Joe** [comment] 2021-07-07 01:10
> Can you post debug logs?

Is this it?

19:54:41: Sneedacity 3.0.4-alpha-20210706
19:54:41: Warning: Cannot set locale to language "English".
19:54:41: Warning: Critical Nyquist files could not be found. Nyquist effects will not work.
19:54:45: Trying to load FFmpeg libraries...
19:54:45: Trying to load FFmpeg libraries from system paths. File name is 'libavformat.so.58'.
19:54:45: Checking for monolithic avformat from 'libavformat.so.58'.
19:54:45: avformat not monolithic
19:54:45: Loading avutil from '/usr/lib/libavutil.so.56.70.100'.
19:54:45: Loading avcodec from '/usr/lib/libavcodec.so.58.134.100'.
19:54:45: Loading avformat from 'libavformat.so.58'.
19:54:45: Actual avutil path /usr/lib/libavutil.so.56.70.100
19:54:45: Actual avcodec path /usr/lib/libavcodec.so.58.134.100
19:54:45: Actual avformat path /usr/lib/libavformat.so.58.76.100
19:54:45: Importing symbols...
19:54:45: All symbols loaded successfully. Initializing the library.
19:54:45: Retrieving FFmpeg library version numbers:
19:54:45:    AVCodec version 0x3a8664 - 58.134.100 (built against 0x3a8664 - 58.134.100)
19:54:45:    AVFormat version 0x3a4c64 - 58.76.100 (built against 0x3a4c64 - 58.76.100)
19:54:45:    AVUtil version 0x384664 - 56.70.100 (built against 0x384664 - 56.70.100)
19:54:45: FFmpeg libraries loaded successfully.

**Comment by Techi-Joe** [comment] 2021-07-07 01:16
> Can you post debug logs?
Oh I just remembered that I had to add a strange tag to makepkg in order for the build to work, here's the command I used in full:
makepkg -csi DOCBOOK_TO_MAN="xmlto man --skip-validation"

Without this the build would fail. I can give you the failed output if you like.

**Comment by ChucksConsulting** [comment] 2021-07-07 01:34
It's not just you, nobody has managed to make the audio effect plugins work. It somehow happened when they replaced all the occurrences or "audacity" for "sneedacity" across the whole project.
I don't see any way out other than reverting back to the initial commit and slowly cherry picking newer commits one by one solving any merge conflicts as they happen.

**Comment by Techi-Joe** [comment] 2021-07-07 01:42
> It's not just you, nobody has managed to make the audio effect plugins work. It somehow happened when they replaced all the occurrences or "audacity" for "sneedacity" across the whole project.
> I don't see any way out other than reverting back to the initial commit and slowly cherry picking newer commits one by one solving any merge conflicts as they happen.

Ok, take note of that strange tag in the makepkg, however. Looks like XML writing might not work on Arch based distros. Too lazy to make new issue out of it myself, however, and I never use XMLs :/

**Comment by ishimotoshinobu** [comment] 2021-07-07 01:47
@Techi-Joe try to rename everything to sneedacity in your xml files instead of audacity

**Comment by Techi-Joe** [comment] 2021-07-07 01:54
> @Techi-Joe try to rename everything to sneedacity in your xml files instead of audacity

Not sure what you mean... this is a build error, not an filename error. And I wouldn't even know where to begin checking XML functionality in Sneedacity. I briefly checked to make sure all mentions of audacity in src/xml had been replaced with sneedacity, and they have.

**Comment by Techi-Joe** [comment] 2021-07-07 02:01
@ishimotoshinobu @ChucksConsulting 

Found this in /sneedacity/src/effects/nyquist/LoadNyquist.cpp:
```
bool NyquistEffectsModule::Initialize()
{
   const auto &sneedacityPathList = FileNames::SneedacityPathList();

   for (size_t i = 0, cnt = sneedacityPathList.size(); i < cnt; i++)
   {
      wxFileName name(sneedacityPathList[i], wxT(""));
      name.AppendDir(wxT("nyquist"));
      name.SetFullName(wxT("nyquist.lsp"));
      if (name.FileExists())
      {
         // set_xlisp_path doesn't handle fn_Str() in Unicode build. May or may not actually work.
         nyx_set_xlisp_path(name.GetPath().ToUTF8());
         return true;
      }
   }

   wxLogWarning(wxT("Critical Nyquist files could not be found. Nyquist effects will not work."));

   return false;
}
```
However wrote this wasn't confident it would work, and it returns the exact error we're getting when false. Possible lead?
(line #126, btw)

**Comment by ishimotoshinobu** [comment] 2021-07-07 02:23
Yep API and ABI have changed I recommend to replace audacity with sneedacity in source files and recompile the plugin

**Comment by Techi-Joe** [comment] 2021-07-07 02:37
@ishimotoshinobu I think I may have found it. In filenames.cpp some interesting spelling occurs:

`
static FilePaths sSneedacityPathList;

const FilePaths &FileNames::SneedacityPathList()
{
   return sSneedacityPathList;
}

void FileNames::SetSneedacityPathList( FilePaths list )
{
   sSneedacityPathList = std::move( list );
}
`

Now I'll be the first to admit that my knowledge of cpp is limited, but I find it weird that an object would sometimes be spelled  sSneedacityPathList and other times be spelled SneedacityPathList. Nonetheless in the exact object that if null would cause NyquistEffectsModule::Initialize() to return false...

line 610.

Would make pull request, but want to make sure I got this right lol.

**Comment by BasedRimuru** [comment] 2021-07-07 02:45
The same happens on Artix here, i can't find the root cause because it also happens on audacity

**Comment by ChucksConsulting** [comment] 2021-07-07 03:07
> @ishimotoshinobu I think I may have found it. In filenames.cpp some interesting spelling occurs:
> 
> ```
> 
> 
> static FilePaths sSneedacityPathList;
> 
> const FilePaths &FileNames::SneedacityPathList()
> {
>    return sSneedacityPathList;
> }
> 
> void FileNames::SetSneedacityPathList( FilePaths list )
> {
>    sSneedacityPathList = std::move( list );
> }
> ```
> 
> Now I'll be the first to admit that my knowledge of cpp is limited, but I find it weird that an object would sometimes be spelled sSneedacityPathList and other times be spelled SneedacityPathList. Nonetheless in the exact object that if null would cause NyquistEffectsModule::Initialize() to return false...
> 
> line 610.
> 
> Would make pull request, but want to make sure I got this right lol.

Unfortunately that's not the case, since the extra s is in Audacity from years ago
https://github.com/audacity/audacity/blob/f86403378be49a71c32a0339c00349b93361ea11/src/FileNames.cpp

**Comment by ChucksConsulting** [comment] 2021-07-07 03:08
> The same happens on Artix here, i can't find the root cause because it also happens on audacity
Try deleting your configs and try again. Normal Audacity works fine from me building from git.

**Comment by ChucksConsulting** [comment] 2021-07-07 03:36
> The same happens on Artix here, i can't find the root cause because it also happens on audacity

Well, now the commit I thought was working doesn't work for me anymore. I don't know wtf is going on.

**Comment by BasedRimuru** [comment] 2021-07-07 03:46
I made some tests here, it's probably related to shared libraries

>building from source on Artix didn't work
>until I installed all audacity libraries from pacman, so it worked on audacity 3.0.4alpha
>however, sneedacity 3.0.4alpha still doesn't work

The only things that weren't renamed on the big rename were some cmake things with conan that were broken when renamed, otherwise everything should be exactly equal

What I think it's weird is that other forks also have the same problem like:
https://github.com/SartoxOnlyGNU/audacium/issues/6
And they changed much less

**Comment by ChucksConsulting** [comment] 2021-07-07 03:47
Sneedacity should be built on 368ab6f88845d1ac7723b6076e508aa4c619b4c6

**Comment by ChucksConsulting** [comment] 2021-07-07 03:48
> I made some tests here, it's probably related to shared libraries
> 
> > building from source on Artix didn't work
> > until I installed all audacity libraries from pacman, so it worked on audacity 3.0.4alpha
> > however, sneedacity 3.0.4alpha still doesn't work
> 
> The only things that weren't renamed on the big rename were some cmake things with conan that were broken when renamed, otherwise everything should be exactly equal
> 
> What I think it's weird is that other forks also have the same problem like:
> [SartoxOnlyGNU#6](https://github.com/SartoxOnlyGNU/audacium/issues/6)
> And they changed much less

Some of the renaming happened in the "remove botnet" commit, right?

**Comment by BasedRimuru** [comment] 2021-07-07 03:50
Yes, here it only works if i go before the remove botnet commit

**Comment by ChucksConsulting** [comment] 2021-07-07 04:01
Then it probably doesn't have much to do with the renaming and it was because of the removal of sentry.
Even after replacing every instance of sneedacity with audacity I get the problem with the filters.

**Comment by WampiFlampi** [comment] 2021-07-07 06:32
Are we able to revert to a stable, pre-botnet version then resneed?

**Comment by BasedRimuru** [comment] 2021-07-07 06:58
It may be hard since the botnet removal commits were squashed together with the 3.0.4 plugin commits, but I though about some possibilities

1. We can try to fix that, I think it may be related with cmake-proxies and conan since there's some instability on the possible fix related to shared libraries. Staying on 3.0.4alpha, even the original audacity doesn't work on some computers like mine, it only started to work after I replaced the libraries via pacman
2. We can try to fix that by copying only the 3.0.2 files related to the plugins, sneedfying them, and adapting to our changes. It may not be that hard since it's just a few files, but there's no guarantees that it will work
3. We can try to do some git magic to clean up the botnet removal commit from 3.0.4alpha code

A thing that I discovered about the bug, is that it happens on two different ways. One is what happened with me: only a few plugins appear on the upstream audacity until you fix the libraries by installing from the package manager, and other is what happens with sneedacity even after you fix the libraries on audacity alpha, fewer or no plugins appear and there's no known solution.

Today is already late, but tomorrow I will try more things:

1. Sneedfying 3.0.2 to see if there's more influence from the mass renaming
2. Trying to understand why audacity's wxWidgets is from a different version
3. Seeing if the based c++ anons are being able to remove conan
4. Inspect what libraries cause the first version of the bug

![822a5aad681a52e5ad0e6020678c392e](https://user-images.githubusercontent.com/86988907/124713454-1a518700-def0-11eb-9cf5-f0636cdcc6ff.png)

So, good night anons! Go to sleep already you guys that are also from american timezone

**Comment by ChucksConsulting** [comment] 2021-07-07 07:33
> It may be hard since the botnet removal commits were squashed together with the 3.0.4 plugin commits, but I though about some possibilities
> 
> 1. We can try to fix that, I think it may be related with cmake-proxies and conan since there's some instability on the possible fix related to shared libraries. Staying on 3.0.4alpha, even the original audacity doesn't work on some computers like mine, it only started to work after I replaced the libraries via pacman
> 2. We can try to fix that by copying only the 3.0.2 files related to the plugins, sneedfying them, and adapting to our changes. It may not be that hard since it's just a few files, but there's no guarantees that it will work
> 3. We can try to do some git magic to clean up the botnet removal commit from 3.0.4alpha code
> 
> A thing that I discovered about the bug, is that it happens on two different ways. One is what happened with me: only a few plugins appear on the upstream audacity until you fix the libraries by installing from the package manager, and other is what happens with sneedacity even after you fix the libraries on audacity alpha, fewer or no plugins appear and there's no known solution.
> 
> Today is already late, but tomorrow I will try more things:
> 
> 1. Sneedfying 3.0.2 to see if there's more influence from the mass renaming
> 2. Trying to understand why audacity's wxWidgets is from a different version
> 3. Seeing if the based c++ anons are being able to remove conan
> 4. Inspect what libraries cause the first version of the bug
> 
> ![822a5aad681a52e5ad0e6020678c392e](https://user-images.githubusercontent.com/86988907/124713454-1a518700-def0-11eb-9cf5-f0636cdcc6ff.png)
> 
> So, good night anons! Go to sleep already you guys that are also from american timezone

I think I might have solved it, check the pull request

**Comment by meguminloli** [comment] 2021-07-07 08:11
>I think might have solved it, check the pull request

So they forgot to add their new plugin manager upstream? kek

**Comment by ChucksConsulting** [comment] 2021-07-07 08:27
> > I think might have solved it, check the pull request
> 
> So they forgot to add their new plugin manager upstream? kek

No, the old files just overwrote some of the broken code they commited as part of the refactoring of the plugin stuff.

**Comment by Ckath** [comment] 2021-07-07 11:39
this and #32 was all fixed with #66 right? can they be closed?

**Comment by ChucksConsulting** [comment] 2021-07-07 12:16
Yeah
But when they fix it upstream there will have to be discussion on how to merge it

**Comment by Ckath** [comment] 2021-07-07 12:18
I'll just close them for now and then they can be reopened/made again when that time comes around. just to make it clear it works atm at least

**Closed by Ckath** 2021-07-07 12:18 UTC
Labels: bug, help wanted
